name: Deploy Scripts

on: 
    push: 
        branches: 
            - main


jobs: 
    deploy-scripts:
        runs-on: self-hosted
        steps:
            - name: Clone gh_env repo
              env: 
                GH_TOKEN: ${{ secrets.GIT_TEST }}
              run: |
                git clone https://oauth2:$GH_TOKEN@github.com/anithajois/gh_env.
                cp _compas-runner-tmp/scripts/deploy.sh aws/tmp_deploy.sh
                rm -rf _compas-runner-tmp
                
              



