name: Deploy Scripts

on: 
    push: 
        branches: 
            - main


jobs: 
    deploy-scripts:
        runs-on: ubuntu-latest
        steps:
            - name: Fetch Deploy.sh directly
              uses: actions/checkout@v3
              env:
                GH_TOKEN: ${{ secrets.GH_PAT }}
              with:
                token: ${{ secrets.GH_PAT }}
                repository: anithajois/gh_env
                github-server-url: https://outh2:$GH_TOKEN@github.com/anithajois/gh_env
                ref: main
                sparse-checkout: scripts/deploy.sh
                path: aws
                run: |
                    git add 
                    git commit -m "adding file"
                    git push

           

        
    


             


