name: Deploy Scripts

on: 
    push: 
        branches: 
            - main


jobs: 
    deploy-scripts:
        runs-on: self-hosted
        steps:
            - name: Checkout to Repo where the scripts are there
              uses: actions/checkout@v4
              with: 
                token: ${{ secrets.GH_TEST }}
                ref: main
                repository: anithajois/gh_env
                github-server-url: https://github.com/
                sparse-checkout: scripts/deploy.sh
                sparse-checkout-cone-mode: false
                path: _compas-runner-tmp

            - name: Copy Deploy.sh into workspace
              run: |
                 cp _compas-runner-tmp/scripts/deploy.sh aws/tmp_deploy.sh
                 rm -rf _compas-runner-tmp
                
              



